### PR TITLE
Get the data from the performance server and insert it in the database

### PR DESCRIPTION
**Pull request by fxleblanc**
### Content
1. The server http request to get the informations about the gpu
2. The insert in the database
### Notes
1. If this pull request passes, we should make an issue about changing the readme.md to add documentation on how to launch the server and run the tests. 
2. Since the database schema changed, we must update the server using this database(if it's already installed)

### CODE REVIEW

**Comment by jdupl** [comment]
No need for an issue to change the read me.
Next task would be to get the servers' ip from a table (machine table).
Also, server information is not to be inserted into stats but in a stats table for servers only.

**Comment by fxleblanc** [comment]
### New issues

Two new issues have been created.
1. The new stats server table creation #11 
2. Ip verification #12

### Notes

Right now, the server infos(not the stats) must be entered directly into the database. Should we make an issue for the future admin frontend?

**Comment by jdupl** [comment]
Issue(s) for the admin section will be determined when the final specs will be decided.
For now, we should focus on m2.
Then, m3 will bring us to have a somewhat working data collector and analyser. 
Perhaps a webui will be for m4.

**Comment by jdupl** [comment]
Looking at the db schema, I plan to modify a lot of data structures and other issues have come to mind.
I wil not merge for now.
Let me modify the data structure and you can then rework your queries.

**Pull request closed without merging**
